using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.SpiritBoard;

[GenerateTypedNameReferences]
public sealed partial class SpiritBoardGhostWindow : DefaultWindow
{
    public Action? OnSend;
    public Action? OnCancel;

    public SpiritBoardGhostWindow()
    {
        RobustXamlLoader.Load(this);
        SendButton.OnPressed += _ => OnSend?.Invoke();
        CancelButton.OnPressed += _ => OnCancel?.Invoke();

    }
}
